name: Release Prepare

on:
  workflow_dispatch:

jobs:
  prepare:
    uses: edalzell/github-workflows/.github/workflows/release-prepare.yml@5ebfc6714a6c4ca7f2434ff01736ea2405e1c323 # v1.3.1
    permissions:
      contents: write
    secrets:
      release_token: ${{ secrets.RELEASE_TOKEN }}
